<!DOCTYPE html>
<html lang="id">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

<title>Home</title>

<link rel="stylesheet" href="http://code.jquery.com/ui/1.10.4/themes/smoothness/jquery-ui.css">
{!! Html::style(elixir('css/appweb.css')) !!}


<link href="https://fonts.googleapis.com/css?family=Noto+Sans" rel="stylesheet">
</head>
<body>

<!-- navbar -->
    @yield('navbar')
    @yield('navbar-red')

    <!-- searchbar -->
    @yield('searchbar')

    <!-- content -->
    @yield('content')

    <!-- footer -->
    @yield('footer')
    @yield('simple-footer')

</body>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.4/jquery.min.js"></script>
<script src="http://code.jquery.com/jquery-1.9.1.js"></script>
<script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
{!! Html::script('js/tether.js') !!}
{!! Html::script(elixir('js/appweb.js')) !!}

<script>
$(document).ready(function(){
adapromo.init();
});
</script>
        <script type="text/javascript">
            $(function () {
                $("#btnsubmit").click(function () {
                    var password = $("#password").val();
                    var confirmPassword = $("#password2").val();
                    if (password != confirmPassword) {
                        alert("Passwords do not match.");
                        return false;
                    }
                    return true;
                });
            });
        </script>
        <script src="http://code.jquery.com/ui/1.10.4/jquery-ui.js"></script>
<script>
    $(function() {
    $( "#tabs" ).tabs();
    });
</script>

<!--<script>
function myFunction() {
    var x = document.getElementById("mySelect").value * document.getElementById("harga").value;
    var num = parseFloat( x ); //convert to float  
    //default values  
    decimalSeparator = ',';  
    thousandsSeparator = '.';  
    nDecimalDigits = 2;  
  
    var fixed = num.toFixed(nDecimalDigits); //limit or add decimal digits  
    //separate begin [$1], middle [$2] and decimal digits [$4]  
    var parts = new RegExp('^(-?\\d{1,3})((?:\\d{3})+)(\\.(\\d{' + nDecimalDigits + '}))?$').exec(fixed);   
  
    if(parts){ //num >= 1000 || num < = -1000  
        document.getElementById("demo").innerHTML = "Rp " + parts[1] + parts[2].replace(/\d{3}/g, thousandsSeparator + '$&') + (parts[4] ? decimalSeparator + parts[4] : '');
         document.getElementById("total").value = x;
    }else{  
        document.getElementById("demo").innerHTML = "Rp " + fixed.replace('.', decimalSeparator);  
    }    
}-->

</script>
<script>
function goBack() {
    window.history.back();
    window.history.back();
}

function goBackProfil() {
    window.history.back();
}
</script>
<script>
  $( function() {
    var availableTags = [
      "Airmadidi",
"Ampana",
"Amurang",
"Andolo",
"Banggai",
"Bantaeng",
"Barru",
"Bau-Bau",
"Benteng",
"Bitung",
"Bolaang Uki",
"Boroko",
"Bulukumba",
"Bungku",
"Buol",
"Buranga",
"Donggala",
"Enrekang",
"Gorontalo",
"Jeneponto",
"Kawangkoan",
"Kendari",
"Kolaka",
"Kotamobagu",
"Kota Raha",
"Kwandang",
"Lasusua",
"Luwuk",
"Majene",
"Makale",
"Makassar (Ujung Pandang)",
"Malili",
"amasa",
"Mamuju",
"Manado (Menado)",
"Marisa",
"Maros",
"Masamba",
"Melonguane",
"Ondong Siau",
"Palopo",
"Palu",
"Pangkajene",
"Pare-Pare",
"Parigi",
"Pasangkayu",
"Pinrang",
"Polewali",
"Poso",
"Rantepao",
"Ratahan",
"Rumbia",
"Sengkang",
"Sidenreng",
"Sigi Biromaru",
"Sinjai",
"Sunggu Minasa",
"Suwawa",
"Tahuna",
"Takalar",
"Tilamuta",
"Toli Toli",
"Tomohon",
"Tondano",
"Tutuyan",
"Unaaha",
"Wangi Wangi",
"Wanggudu",
"Watampone",
"Watan Soppeng",
"Cliquers",
"Libuo Palma",
"Aek Kanopan",
"Arga Makmur",
"Arosuka",
"Balige",
"Banda Aceh",
"Bandar Lampung",
"Bagansiapiapi",
"Baganbatu",
"Bandar Seri Bintan",
"Bangkinang",
"Bangko",
"Banyuasin",
"Batam",
"Baturaja",
"Batusangkar",
"Bengkalis",
"Bengkulu",
"Binjai",
"Bintuhan",
"Bireuen",
"Blambangan Umpu",
"Blangpidie",
"Blang Kejeren",
"Bukittinggi",
"Calang",
"Curup",
"Daik",
"Dolok Marawa",
"Dumai",
"Gedong Tataan",
"Gunung Sitoli",
"Gunung Sugih",
"Gunung Tua",
"Idi Rayeuk",
"Indralaya",
"Jambi",
"Jantho",
"Kabanjahe",
"Kalianda",
"Karang Baru",
"Karang Tinggi",
"Kayu Agung",
"Kepahiang",
"Kisaran",
"Koba",
"Kota Agung",
"Kotabumi",
"Kota Pinang",
"Kuala Tungkal",
"Kutacane",
"Lahat",
"Lahomi",
"Langsa",
"Lhokseumawe",
"Lhoksukon",
"Limapuluh",
"Liwa",
"Lotu",
"Lubuk Basung",
"Lubuk Bendaharo",
"Lubuk Linggau",
"Lubuk Pakam",
"Lubuk Sikaping",
"Manggar",
"Manna",
"Martapura (Sumatera Selatan)",
"Medan",
"Menggala",
"Mentok",
"Metro",
"Meulaboh",
"Meureude",
"Muara Aman",
"Muara Bulian",
"Muara Bungo",
"Muara Dua",
"Muara Enim",
"Muara Sabak",
"Muara Tebo",
"Muaro Sijunjung",
"Mukomuko",
"Padang",
"Padang Aro",
"Padang Panjang",
"Padang Sidempuan",
"Pagaralam",
"Painan",
"Palembang",
"Pandan",
"Pangkalan Kerinci",
"Pangkal Pinang",
"Panguruan",
"Panyabungan",
"Pariaman",
"Parit Malintang",
"Pasir Pengarayan",
"Payakumbuh",
"Pekanbaru",
"Pematang Siantar",
"Prabumulih",
"Pringsewu",
"Pulau Punjung",
"Ranai",
"Rantau Prapat",
"Raya",
"Rengat",
"Sabang",
"Salak",
"Sarila",
"Sarolangun",
"Sawahlunto",
"Sei Rampah",
"Sekayu",
"Selat Panjang",
"Sengeti",
"Siak Sri Indrapura",
"Sibolga",
"Sibuhuan",
"Sidikalang",
"Sigli",
"Simpang Ampek",
"Simpang Tiga Redelong",
"Sinabang",
"Singkil",
"Sipirok",
"Solok",
"Stabat",
"Subulussalam",
"Sukadana",
"Suka Makmue",
"Sungailiat",
"Sungai Penuh",
"Takengon",
"Tais",
"Tanjung Balai (Sumatera Utara)",
"Tanjung Balai Karimun (Kepulauan Riau)",
"Tanjung Enim",
"Tanjung Pandan",
"Tanjung Pinang",
"Tapaktuan",
"Tarempa",
"Tarutung",
"Tebing Tinggi (Sumatera Utara)",
"Tebing Tinggi (Sumatera Selatan)",
"Teluk Dalam",
"Teluk Kuantan",
"Tembilahan",
"Toboali",
"Tuapejat",
"Ujung Tanjung",
"Ambarawa",
"Anyer",
"Bandung",
"Bangil",
"Banjar (Jawa Barat)",
"Banjarnegara",
"Bangkalan",
"Bantul",
"Banyumas",
"Banyuwangi",
"Batang",
"Batu",
"Bekasi",
"Blitar",
"Blora",
"Bogor",
"Bojonegoro",
"Bondowoso",
"Boyolali",
"Bumiayu",
"Brebes",
"Caruban",
"Cianjur",
"Ciamis",
"Cibinong",
"Cikampek",
"Cikarang",
"Cilacap",
"Cilegon",
"Cirebon",
"Demak",
"Depok",
"Garut",
"Gresik",
"Indramayu",
"Jakarta",
"Jember",
"Jepara",
"Jombang",
"Kajen",
"Karanganyar",
"Kebumen",
"Kediri",
"Kendal",
"Kepanjen",
"Klaten",
"Kota Palabuhanratu",
"Kraksaan",
"Kudus",
"Kuningan",
"Lamongan",
"Lumajang",
"Madiun",
"Magelang",
"Magetan",
"Majalengka",
"Malang",
"Mojokerto",
"Mojosari",
"Mungkid",
"Ngamprah",
"Nganjuk",
"Ngawi",
"Pacitan",
"Palabuhanratu",
"Pamekasan",
"Pandeglang",
"Pare",
"Pati",
"Pasuruan",
"Pekalongan",
"Pelabuhan Ratu",
"Pemalang",
"Ponorogo",
"Probolinggo",
"Purbalingga",
"Purwakarta",
"Purwodadi",
"Purwokerto",
"Purworejo",
"Rangkasbitung",
"Rembang",
"Salatiga",
"Sampang",
"Semarang",
"Serang",
"Sidayu",
"Sidoarjo",
"Singaparna",
"Situbondo",
"Slawi",
"Sleman",
"Soreang",
"Sragen",
"Subang",
"Sukabumi",
"Sukoharjo",
"Sumber",
"Sumedang",
"Sumenep",
"Surabaya",
"Surakarta",
"Tasikmalaya",
"Tangerang",
"Tangerang Selatan",
"Tegal",
"Temanggung",
"Tigaraksa",
"Trenggalek",
"Tuban",
"Tulungagung",
"Ungaran",
"Wates",
"Wlingi",
"Wonogiri",
"Wonosari",
"Wonosobo",
"Yogyakarta",
"Atambua",
"Baa",
"Badung",
"Bajawa",
"Bangli",
"Bima",
"Denpasar",
"Dompu",
"Ende",
"Gianyar",
"Kalabahi",
"Karangasem",
"Kefamenanu",
"Klungkung",
"Kupang",
"Labuhan Bajo",
"Larantuka",
"Lewoleba",
"Maumere",
"Mataram",
"Mbay",
"Negara",
"Praya",
"Raba",
"Ruteng",
"Selong",
"Singaraja",
"Soe",
"Sumbawa Besar",
"Tabanan",
"Taliwang",
"Tambolaka",
"Tanjung (Nusa Tenggara Barat)",
"Waibakul",
"Waikabubak",
"Waingapu",
"Denpasar",
"Negara,Bali",
"Singaraja",
"Tabanan",
"Bangli",
"Pontianak",
"Samarinda",
"Banjarmasin",
"Balikpapan",
"Singkawang",
"Palangkaraya",
"Mempawah",
"Ketapang",
"Sintang",
"Tarakan",
"Putussibau",
"Sambas",
"Sampit",
"Banjarbaru",
"Barabai",
"Batang Tarang",
"Batulicin",
"Bengkayang",
"Bontang",
"Buntok",
"Kandangan",
"Kendawangan",
"Kotabaru",
"Kuala Kapuas",
"Kuala Kurun",
"Kuala Pembuang",
"Malinau",
"Marabahan",
"Martapura",
"Muara Teweh",
"Nanga Bulik",
"Nanga Pinoh",
"Ngabang",
"Nunukan",
"Pangkalan Bun",
"Paringin",
"Pelaihari",
"Penajam",
"Pulang Pisau",
"Purukcahu",
"Rantau",
"Sangatta",
"Sebatik",
"Sekadau",
"Sendawar",
"Sukadana",
"Sukamara",
"Sungai Raya",
"Tamiang Layang",
"Tanah Grogot",
"Tanjung",
"Tanjung Selor",
"Tanjung Redeb",
"Tenggarong",
"Ambon",
"Asmat",
"Biak",
"Bintuni",
"Boven Digoel",
"Buru Selatan",
"Buru",
"Deiyai",
"Dogiyai",
"Fakfak",
"Halmahera Barat",
"Halmahera Selatan",
"Halmahera Tengah",
"Halmahera Timur",
"Halmahera Utara",
"Intan Jaya",
"Jayapura",
"Jayapura (kota)",
"Jayawijaya",
"Kaimana",
"Keerom",
"Kepulauan Aru",
"Kepulauan Sula",
"Kepulauan Yapen",
"Lanny Jaya",
"Maluku Barat Daya",
"Maluku Tengah",
"Maluku Tenggara",
"Maluku Tenggara Barat",
"Mamberamo Raya",
"Mamberamo Tengah",
"Manokwari",
"Manokwari Selatan",
"Mappi",
"Maybrat",
"Merauke",
"Mimika",
"Nabire",
"Nduga",
"Paniai",
"Pegunungan Arfak",
"Pegunungan Bintang",
"Pulau Morotai",
"Pulau Taliabu",
"Puncak",
"Puncak Jaya",
"Raja Ampat",
"Sarmi",
"Seram Bagian Barat",
"Seram Bagian Timur",
"Sorong",
"Sorong Selatan",
"Supiori",
"Tambrauw",
"Teluk Bintuni",
"Teluk Wondama",
"Ternate",
"Tidore",
"Tolikara",
"Tual",
"Waropen",
"Yahukimo",
"Yalimo"

    ];
    $( "#tags" ).autocomplete({
      source: availableTags
    });
  } );
  </script>
<!--<script>
$('#exampleModal').on('show.bs.modal', function (event) {
  var button = $(event.relatedTarget) // Button that triggered the modal
  var recipient = button.data('whatever') // Extract info from data-* attributes
  // If necessary, you could initiate an AJAX request here (and then do the updating in a callback).
  // Update the modal's content. We'll use jQuery here, but you could use a data binding library or other methods instead.
  var modal = $(this)
  modal.find('.modal-title').text('LOGIN FOR ' + recipient)
})
</script>-->
    

@yield('js')
</html>